//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Meimad.Planner.Server")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1.2.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.2+078b6d2e3abc6a5d259e782401be93d8be2eb2bc")]
[assembly: System.Reflection.AssemblyProductAttribute("Meimad.Planner.Server")]
[assembly: System.Reflection.AssemblyTitleAttribute("Meimad.Planner.Server")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1.2.0")]

// Generated by the MSBuild WriteCodeFragment class.

