"use strict";

const ids = ["serverHost", "serverPort", "databaseName", "viewSchema", "viewName",
  "username", "password", "clearPassword", "enabled", "refreshIntervalSeconds"];
const elements = Object.fromEntries(ids.map(id => [id, document.getElementById(id)]));
const statusBadge = document.getElementById("statusBadge");
const mappingBadge = document.getElementById("mappingBadge");
const message = document.getElementById("message");
const testSummary = document.getElementById("testSummary");
const testTime = document.getElementById("testTime");
const passwordState = document.getElementById("passwordState");
const columns = document.getElementById("columns");
const columnPanel = document.getElementById("columnPanel");
const mappingRows = document.getElementById("mappingRows");
const mappingSummary = document.getElementById("mappingSummary");
const mappingStatus = document.getElementById("mappingStatus");
const mappingNotes = document.getElementById("mappingNotes");
const sourceColumnChoices = document.getElementById("sourceColumnChoices");
let currentVersion = 0;
let mappingVersion = 0;
let mappingFields = [];
let detectedColumns = [];

const confidenceOptions = ["high", "medium", "low", "blocked"];
const transformOptions = ["direct", "trim", "trim_or_null", "positive_integer", "positive_int",
  "date_only", "ordered_position", "manual_lookup", "generated_working_folder", "seconds",
  "hours_to_seconds_pending", "unmapped"];

async function request(path, options) {
  const response = await fetch(path, options);
  let body = null;
  try { body = await response.json(); } catch { }
  if (!response.ok) {
    const text = body?.error?.message || body?.message || `${response.status} ${response.statusText}`;
    const error = new Error(text);
    error.body = body;
    throw error;
  }
  return body;
}

function setBusy(busy) {
  document.querySelectorAll("button").forEach(button => button.disabled = busy);
}

function showMessage(text, succeeded = false) {
  message.textContent = text;
  message.style.color = succeeded ? "#0b5f38" : "#9d231b";
}

function showSettings(value) {
  currentVersion = value.version;
  elements.serverHost.value = value.serverHost;
  elements.serverPort.value = value.serverPort;
  elements.databaseName.value = value.databaseName;
  elements.viewSchema.value = value.viewSchema;
  elements.viewName.value = value.viewName;
  elements.username.value = value.username;
  elements.password.value = "";
  elements.clearPassword.checked = false;
  elements.enabled.checked = value.enabled;
  elements.refreshIntervalSeconds.value = value.refreshIntervalSeconds;
  passwordState.textContent = value.passwordConfigured
    ? "An encrypted password is stored on this Server."
    : "No password is stored.";
  const status = value.lastTestStatus.replaceAll("_", " ");
  statusBadge.textContent = `Connection: ${status}`;
  statusBadge.className = `badge ${value.lastTestStatus === "succeeded" ? "success" : value.lastTestStatus === "failed" ? "failed" : "neutral"}`;
  testSummary.textContent = value.lastTestMessage || "Not tested.";
  testTime.textContent = value.lastTestAt ? `Tested ${new Date(value.lastTestAt).toLocaleString()}` : "";
}

function selectedMode() {
  return document.querySelector('input[name="modelMode"]:checked')?.value || "domain_aligned";
}

function option(value, selected) {
  const item = document.createElement("option");
  item.value = value;
  item.textContent = value.replaceAll("_", " ");
  item.selected = value === selected;
  return item;
}

function sourceInput(field) {
  const input = document.createElement("input");
  input.className = "mapping-source";
  input.setAttribute("list", "sourceColumnChoices");
  input.maxLength = 128;
  input.value = field.sourceColumn || "";
  input.placeholder = field.transform === "generated_working_folder" ? "Generated by Server" : "Choose or type a column";
  if (field.transform === "generated_working_folder") input.disabled = true;
  input.addEventListener("input", updateMappingSummary);
  return input;
}

function renderMappings() {
  mappingRows.replaceChildren();
  const mode = selectedMode();
  let lastEntity = null;
  mappingFields.forEach((field, index) => {
    const applies = field.modelModes.includes(mode);
    if (field.targetEntity !== lastEntity) {
      lastEntity = field.targetEntity;
      const group = document.createElement("tr");
      group.className = `group-row${applies ? "" : " inactive-mode"}`;
      group.dataset.entity = field.targetEntity;
      const cell = document.createElement("td");
      cell.colSpan = 6;
      cell.textContent = field.targetEntity.replaceAll("_", " ");
      group.append(cell);
      mappingRows.append(group);
    }
    const row = document.createElement("tr");
    row.dataset.index = index;
    row.className = applies ? "" : "inactive-mode";

    const enabledCell = document.createElement("td");
    const enabled = document.createElement("input");
    enabled.type = "checkbox";
    enabled.className = "mapping-enabled";
    enabled.checked = field.enabled;
    enabled.disabled = field.required && applies;
    enabled.addEventListener("change", updateMappingSummary);
    enabledCell.append(enabled);

    const targetCell = document.createElement("td");
    targetCell.className = "target-title";
    const title = document.createElement("strong");
    title.textContent = field.displayName;
    if (field.required) {
      const mark = document.createElement("span");
      mark.className = "required-mark";
      mark.textContent = " *";
      title.append(mark);
    }
    const code = document.createElement("code");
    code.textContent = `${field.targetEntity}.${field.targetField}`;
    const description = document.createElement("small");
    description.textContent = field.description;
    targetCell.append(title, code, description);

    const sourceCell = document.createElement("td");
    sourceCell.append(sourceInput(field));

    const confidenceCell = document.createElement("td");
    const confidence = document.createElement("select");
    confidence.className = "mapping-confidence";
    confidenceOptions.forEach(value => confidence.append(option(value, field.confidence)));
    confidence.addEventListener("change", updateMappingSummary);
    confidenceCell.append(confidence);

    const transformCell = document.createElement("td");
    const transform = document.createElement("select");
    transform.className = "mapping-transform";
    transformOptions.forEach(value => transform.append(option(value, field.transform)));
    transform.addEventListener("change", event => {
      const source = row.querySelector(".mapping-source");
      source.disabled = event.target.value === "generated_working_folder";
      if (source.disabled) source.value = "";
      updateMappingSummary();
    });
    transformCell.append(transform);

    const notesCell = document.createElement("td");
    const notes = document.createElement("input");
    notes.className = "mapping-notes";
    notes.maxLength = 1000;
    notes.value = field.notes || "";
    notes.placeholder = field.confidence === "blocked" ? "Explain what must be confirmed" : "Optional note";
    notesCell.append(notes);

    row.append(enabledCell, targetCell, sourceCell, confidenceCell, transformCell, notesCell);
    mappingRows.append(row);
  });
  updateMappingSummary();
}

function collectFields() {
  return mappingFields.map((field, index) => {
    const row = mappingRows.querySelector(`tr[data-index="${index}"]`);
    return {
      targetEntity: field.targetEntity,
      targetField: field.targetField,
      enabled: row.querySelector(".mapping-enabled").checked,
      sourceColumn: row.querySelector(".mapping-source").value.trim() || null,
      confidence: row.querySelector(".mapping-confidence").value,
      transform: row.querySelector(".mapping-transform").value,
      notes: row.querySelector(".mapping-notes").value.trim() || null
    };
  });
}

function updateMappingSummary() {
  if (!mappingFields.length) return;
  const mode = selectedMode();
  const current = collectFields();
  const active = current.filter((_, index) => mappingFields[index].modelModes.includes(mode));
  const enabled = active.filter(field => field.enabled);
  const blocked = enabled.filter(field => field.confidence === "blocked").length;
  const missing = enabled.filter(field => !field.sourceColumn && field.transform !== "generated_working_folder").length;
  const detected = new Set(detectedColumns.map(column => column.name.toLowerCase()));
  const unknown = detected.size === 0 ? 0 : enabled.filter(field => field.sourceColumn && !detected.has(field.sourceColumn.toLowerCase())).length;
  mappingSummary.textContent = `${mode.replaceAll("_", " ")}: ${enabled.length} enabled field(s), ${missing} missing source, ${blocked} blocked, ${unknown} not found in the last detected column set. ${detectedColumns.length} source column(s) are available.`;
}

function showMapping(value) {
  mappingVersion = value.version;
  mappingFields = value.fields;
  detectedColumns = value.detectedColumns || [];
  const mode = document.querySelector(`input[name="modelMode"][value="${value.modelMode}"]`);
  if (mode) mode.checked = true;
  mappingStatus.value = value.status;
  mappingNotes.value = value.notes || "";
  mappingBadge.textContent = `Mapping: ${value.status.replaceAll("_", " ")}`;
  mappingBadge.className = `badge ${value.status === "ready_for_implementation" ? "success" : "neutral"}`;

  sourceColumnChoices.replaceChildren();
  detectedColumns.forEach(column => {
    const item = document.createElement("option");
    item.value = column.name;
    item.label = `${column.name} · ${column.dataType}`;
    sourceColumnChoices.append(item);
  });
  columns.replaceChildren();
  detectedColumns.forEach(item => {
    const row = document.createElement("div");
    row.className = "column";
    row.textContent = `${item.name} · ${item.dataType}`;
    columns.append(row);
  });
  columnPanel.hidden = detectedColumns.length === 0;
  renderMappings();
}

async function loadConnection() {
  showSettings(await request("/api/v1/kitaron/connection"));
}

async function loadMapping() {
  showMapping(await request("/api/v1/kitaron/mapping"));
}

async function load() {
  setBusy(true);
  message.textContent = "";
  try { await Promise.all([loadConnection(), loadMapping()]); }
  catch (error) { showMessage(error.message); }
  finally { setBusy(false); }
}

document.getElementById("connectionForm").addEventListener("submit", async event => {
  event.preventDefault();
  setBusy(true);
  message.textContent = "";
  try {
    const value = await request("/api/v1/kitaron/connection", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        serverHost: elements.serverHost.value,
        serverPort: Number(elements.serverPort.value),
        databaseName: elements.databaseName.value,
        viewSchema: elements.viewSchema.value,
        viewName: elements.viewName.value,
        username: elements.username.value,
        password: elements.password.value || null,
        clearPassword: elements.clearPassword.checked,
        enabled: elements.enabled.checked,
        refreshIntervalSeconds: Number(elements.refreshIntervalSeconds.value),
        version: currentVersion
      })
    });
    showSettings(value);
    showMessage("Connection saved. Test it to refresh the source-column choices.", true);
  } catch (error) { showMessage(error.message); }
  finally { setBusy(false); }
});

document.getElementById("testButton").addEventListener("click", async () => {
  setBusy(true);
  message.textContent = "Testing the read-only SQL Server view…";
  message.style.color = "#33475b";
  try {
    const result = await request("/api/v1/kitaron/connection/test", { method: "POST" });
    showSettings(result.settings);
    await loadMapping();
    showMessage(result.message, true);
  } catch (error) {
    if (error.body?.settings) showSettings(error.body.settings);
    showMessage(error.message);
  } finally { setBusy(false); }
});

document.querySelectorAll('input[name="modelMode"]').forEach(input =>
  input.addEventListener("change", renderMappings));

document.getElementById("suggestButton").addEventListener("click", () => {
  const detected = new Map(detectedColumns.map(column => [column.name.toLowerCase(), column.name]));
  let changed = 0;
  mappingFields.forEach((field, index) => {
    if (!field.modelModes.includes(selectedMode())) return;
    const row = mappingRows.querySelector(`tr[data-index="${index}"]`);
    const source = row.querySelector(".mapping-source");
    if (source.disabled) return;
    const existingIsDetected = source.value && detected.has(source.value.toLowerCase());
    if (existingIsDetected) return;
    const suggestion = field.suggestedSourceColumns
      .map(name => detected.get(name.toLowerCase()))
      .find(Boolean);
    if (suggestion) {
      source.value = suggestion;
      changed++;
    }
  });
  updateMappingSummary();
  showMessage(changed ? `${changed} mapping field(s) were matched to detected columns. Review before saving.` : "No additional exact alias matches were found.", changed > 0);
});

document.getElementById("saveMappingButton").addEventListener("click", async () => {
  setBusy(true);
  message.textContent = "";
  try {
    const value = await request("/api/v1/kitaron/mapping", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        modelMode: selectedMode(),
        status: mappingStatus.value,
        fields: collectFields(),
        notes: mappingNotes.value.trim() || null,
        version: mappingVersion
      })
    });
    showMapping(value);
    showMessage("Mapping draft saved on the Server. Import remains disabled.", true);
  } catch (error) { showMessage(error.message); }
  finally { setBusy(false); }
});

document.getElementById("exportButton").addEventListener("click", () => {
  const payload = {
    mappingVersion: 1,
    exportedAt: new Date().toISOString(),
    modelMode: selectedMode(),
    status: mappingStatus.value,
    source: {
      database: elements.databaseName.value,
      schema: elements.viewSchema.value,
      view: elements.viewName.value
    },
    fields: collectFields(),
    notes: mappingNotes.value.trim() || null,
    importEnabled: false
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "kitaron-meimad-mapping-draft.json";
  link.click();
  URL.revokeObjectURL(link.href);
});

document.getElementById("reloadButton").addEventListener("click", load);
document.getElementById("reloadMappingButton").addEventListener("click", async () => {
  setBusy(true);
  try { await loadMapping(); showMessage("Saved mapping reloaded.", true); }
  catch (error) { showMessage(error.message); }
  finally { setBusy(false); }
});

load();
