[platformio]
default_envs = xiao-esp32s3-plus

[env:xiao-esp32s3-plus]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_type = debug
build_flags =
    -D MEIMAD_FIRMWARE_VERSION=\"0.1.0-mvp\"
    -D MEIMAD_HARDWARE_PROFILE=\"trmnl-7.5-og-xiao-esp32s3-plus\"
    -D MEIMAD_EINK_DRIVER_STUB=0
    -D BOARD_SCREEN_COMBO=502
    -D USE_XIAO_EPAPER_DISPLAY_BOARD_EE04
lib_deps =
    zinggjm/GxEPD2@^1.6.0
    adafruit/Adafruit GFX Library@^1.12.1
    bblanchon/ArduinoJson@^7.4.2
    https://github.com/Seeed-Studio/Seeed_GFX.git

[env:xiao-esp32s3-plus-contract-tests]
extends = env:xiao-esp32s3-plus
build_src_filter =
    -<*>
    +<../test/test_tablet_api/test_main.cpp>

[env:xiao-esp32s3-plus-demo]
extends = env:xiao-esp32s3-plus
build_flags =
    ${env:xiao-esp32s3-plus.build_flags}
    -D MEIMAD_DEMO_MODE=1
